name: Env transfer (master)
on:
  push:
    branches:
      - envs
jobs:
  build:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Build ENVS
        run: |
          mkdir ENV &&
          echo API_BASE_PATH=${{ secrets.API_BASE_PATH }} >> ENV/envs
          echo APP_UPDATES_BASE_URL=${{ secrets.APP_UPDATES_BASE_URL }} >> ENV/envs
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> ENV/envs
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ENV/envs
          echo CDN_BASE_URL=${{ secrets.CDN_BASE_URL }} >> ENV/envs
          echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> ENV/envs
          echo MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }} >> ENV/envs
          echo MQTT_PORT=${{ secrets.MQTT_PORT }} >> ENV/envs
          echo MQTT_URL=${{ secrets.MQTT_URL }} >> ENV/envs
          echo MQTT_USERNAME=${{ secrets.MQTT_USERNAME }} >> ENV/envs
          echo SIGN_KEYSTORE=${{ secrets.SIGN_KEYSTORE }} >> ENV/envs
          echo SIGN_KEY_PASSWORD=${{ secrets.SIGN_KEY_PASSWORD }} >> ENV/envs
          echo SIGN_STORE_PASSWORD=${{ secrets.SIGN_STORE_PASSWORD }} >> ENV/envs
          echo UPDATES_BUCKET=${{ secrets.UPDATES_BUCKET }} >> ENV/envs
      - name: Upload ENV
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.UPDATES_BUCKET }}
          source_dir: ENV
          destination_dir: "production"
